os: linux
dist: bionic
language: c
compiler: gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libopenal-dev libmpg123-dev libflac-dev
  - git clone https://github.com/StjepanPoljak/Melodeer
  - (cd Melodeer; cmake . && make)
script:
  - make
